### ISSUE TITLE
remove the Size column

### ISSUE THREAD

**Issue by JianguoRao** [icatproject/topcat_ijp_plugin#10]
In Browse window, there are dataset name, Size, etc. In our case, the Size causes a lot of problems and we don't need it. 

It delays the browser and sometimes frozen the window as well. The current get Size seems having not been properly implemented. It seems that the size information is calculated each time when the browser updated and the size of dataset file is not in the database. It looks like, every time the browser update,  the back-end code goes through the file system to get the Size information of all the datasets.

**Comment by brianritchie1312** [comment]
The Size column has been removed from the Browse view in the configuration for the Octopus development system. I'm not convinced it should be removed from the project's copy of the configuration (it is slightly easier to remove it than to add it). This means that we need to remember to remove it when updating the system, but the configuration is necessarily different in any case.
