### ISSUE TITLE
"ijpUrl: unexpected attribute" on page load

### ISSUE THREAD

**Issue by brianritchie1312** [icatproject/topcat_ijp_plugin#19]
Using the IJP plugin with topcat 2.2.0, the following error dialog appears on page load (or reload):

    Invalid topcat.json: 

    facilities > 0 > ijpUrl: unexpected attribute

![Uploading Screenshot 2016-11-14 17.23.47.png…]()

The GUI works after clicking OK; but this needs to be fixed.

**Comment by rebeccafair** [comment]
I haven't tested it but I suspect this may be due to TopCAT changing the way the schema is defined in 2.2.0.  See icatproject/topcat@1a00027b6e5bcf73abb7f0c262372fc2e6fcb750, configSchema in plugin.js probably needs to change to match this
