### ISSUE TITLE
Change behaviour of dataset browse highlighting/selection/activating

### ISSUE THREAD

**Issue by danrolfe** [icatproject/topcat_ijp_plugin#21]
1. Clicking dataset name in a row should not drill down to datafiles browse view. See #27.
2. Activating the row so its dataset parameters are shown at the bottom should highlight the row in a different colour. There should some indication of the highlight colour in the dataset details view. See #28.
3. A button in dataset details should provide access to the dataset's datafiles browse view. See #27.

**Comment by TickleThePanda** [comment]
If Topcat provides the functionality to change the table's behaviour, this shouldn't be too bad but I need to look into whether Topcat does provide the functionality.

**Comment by TickleThePanda** [comment]
@danrolfe I've split this into multiple issues to make it easier to manage:
 - #27
 - #28
