### ISSUE TITLE
The job submission modal should handle multiple datasets differently, depending on the job type configuration

### ISSUE THREAD

**Issue by danrolfe** [icatproject/topcat_ijp_plugin#22]
Modify the job submission modal so that, depending on how the job type specifies how the job handles multiple datasets, it should:

- when the job must run one per dataset, not give the user an option,
- when the job must run on all datasets, not give the user an option,
- when the job can do either, present the user with the option.

Requires icatproject/ijp.server#48

**Comment by brianritchie1312** [comment]
Closing this - ijp.server #48 was closed in Dec 2016.
