### ISSUE TITLE
No link between "My job" and dataset 

### ISSUE THREAD

**Issue by JianguoRao** [icatproject/topcat_ijp_plugin#3]
On the "My job" page, I can see a list of jobs with the following information:
## Job id, Job Type, Submitted Status Actions

We need a column for the completed job, a dataset id and Name, so that user can
see the relationship of the listed job and the dataset produced.

**Comment by TickleThePanda** [comment]
closed by #24

**Comment by JianguoRao** [comment]
The interface not change at all, why close the issue?

**Comment by brianritchie1312** [comment]
The change is in Github, but not yet deployed.
