### ISSUE TITLE
Worker nodes run more than on quincy jobs

### ISSUE THREAD

**Issue by JianguoRao** [icatproject/topcat_ijp_plugin#32]
The ijp system should be configured such that at any time, each worker only runs one quincy job.

**Comment by brianritchie1312** [comment]
See [icatproject/ijp.torque/#5](https://github.com/icatproject/ijp.torque/issues/5). I had modified server_priv/nodes to set np=6 for vm77, thinking that would enable Torque to take advantage of its 6 cores. I will try setting np back to 1, which should result in only one job running on vm77 at a time.

**Comment by alastairduncan** [comment]
The testing of changes to the server seems to be a bit clunky. When a change is made I think that we(whoever has made the change) should fire off the tests that would test the configuration change.
