### ISSUE TITLE
IJP dosen't not register scripts to ICAT APPLICATION table

### ISSUE THREAD

**Issue by JianguoRao** [icatproject/topcat_ijp_plugin#38]
The add provenance failed because, the application is not registered in APPLICATION table in icat database!

File "/opt/ijp/bin/create_group_PI.py", line 400, in
putDataBacktoICAT(session,options,datasetIdlist,outputfile,ijpUrl,ijpJobId)
File "/opt/ijp/bin/create_group_PI.py", line 297, in putDataBacktoICAT
application = session.getApplication('Create Group list(PI)', "1.0")
File "/usr/local/lib/python2.7/dist-packages/ijp_lsf/lsf_utils_PI.py", line 279, in getApplication
if len(apps) == 0: raise Exception("No Application " + name + " " + version + " for facility " + self.facility.name)
Exception: No Application Create Group list(PI) 1.0 for facility LSF

**Comment by JianguoRao** [comment]
Please treat this as high priority as it blocks testing the provenance feature.

**Comment by brianritchie1312** [comment]
This was fixed by https://github.com/icatproject/ijp.server/commit/5d96e0869ba2cc4c58bc7d289ac7cb60b2142012. But note that the application name used in the jobscript must match the name of the jobtype.
