### ISSUE TITLE
"My Data" is empty and why?

### ISSUE THREAD

**Issue by JianguoRao** [icatproject/topcat_ijp_plugin#4]
I don't know why we have a "My Data" page without any data in it. What data should be on the list of "My Data"?  Should it be any data ingested by myself? or data belong to the same investigation with which a current user associated?

**Comment by brianritchie1312** [comment]
My Data shows any data under any Investigation for which the current user is an InvestigationUser. That it's empty suggests that the user (simple/dmf?) is not associated with any investigations - I will have to investigate.
