### ISSUE TITLE
Where is the equivalent view to old IJP interface? 

### ISSUE THREAD

**Issue by JianguoRao** [icatproject/topcat_ijp_plugin#5]

**Comment by danrolfe** [comment]
We urgently need the view as in the old web interface where we see the dataset parameters for our selected dataset underneath the list of datasets.

**Comment by brianritchie1312** [comment]
The view (or rather its equivalent) is available: click on the blank space in any cell on a dataset row (e.g. in the Size column, as the Name column often has no blank space) to bring it up (and click again to hide it).

**Comment by TickleThePanda** [comment]
Closed by #16 and #18
