### ISSUE TITLE
Add labels and milestones in this issue tracker

### ISSUE THREAD

**Issue by JianguoRao** [icatproject/topcat_ijp_plugin#9]
labels:
bug
enhancement
critical
minor
major

**Comment by brianritchie1312** [comment]
I've added labels for critical, major and minor. I've yet to add Milestones. The approach used in other ICAT components is to have a milestone for each release; but the IJP GUI plugin has never been formally released and the version in the pom is 0.1.0-SNAPSHOT. I don't think that the first release should be 0.1.0.

**Comment by alastairduncan** [comment]
It would be good if the labels for critical major and minor matched the ones in ijp-server.

**Comment by brianritchie1312** [comment]
I've replaced critical / major / minor with Priority-Critical / High / Medium / Low, which match labels already in use in ijp.server (modulo colouring). It looks like there has been a clash between labels from googlecode days and labels that are intrinsic to Github. I'm not sure which should win! It is easier to change labels that have not been used in issues already.

**Comment by alastairduncan** [comment]
I've also seen the "In Progress" labels are these needed? It would be nice to be able to filter on issues that are in progress/or blocked etc. We should be able to use the waffle.io view to see issues that are ready, in progress or done. Are specific labels used to move these to the appropriate column in waffle.io?

**Comment by brianritchie1312** [comment]
I don't know enough about waffle.io to answer this. I think that wafffle.io manages the 'ready' and 'in progress' labels; I don't know whether it reacts if these are added or removed by something/someone else. This project doesn't seem to be in waffle yet.

**Comment by alastairduncan** [comment]
Oh yes it is:

https://waffle.io/icatproject/topcat_ijp_plugin

There's nothing in the 'ready' or in 'progress states' but there are some issues on 'done' so I suspect that it resisters the close in github but what pushes it into the other states - I don't know. Is Steve in? Could you ask him.

**Comment by alastairduncan** [comment]
https://github.com/waffleio/waffle.io/wiki/FAQs#prs-and-issues

It appears that you can get waffle to move the issue automatically if you create an appropriately labelled branch and this is ok if you have code but not for other issues. For these you have to drag the issue, in waffle, to the appropriate column manually.

**Comment by fisherab** [comment]
It was only half in. I have now added it to the main icatproject board so
that the status of all components can be seen.

**Comment by fisherab** [comment]
I manage ready and in progress manually from waffle by dragging the issue.
They do get closed automatically with fix (or various other magic keywords
#9) but this only happens when the commit is on master. If you you commit
to a branch and then merge the branch back in the issue is closed for you.

You will need to use the filter box to get the view you want

**Comment by alastairduncan** [comment]
You can view the project independently of icatproject by using the project name after icatproject

https://waffle.io/icatproject/topcat_ijp_plugin

so no need for filters
